/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.valdi.animedownloader.java-application-conventions")

    // Java fx
    id ("org.openjfx.javafxplugin") version "0.0.10"

    /*
     * Adds tasks to export a runnable jar.
     * In order to create it, launch the "shadowJar" task.
     * The runnable jar will be found in build/libs/projectname-all.jar
     */
    id("com.github.johnrengelman.shadow") version "7.0.0"
}

javafx {
    version = "11.0.2"
    modules("javafx.controls", "javafx.fxml", "javafx.web")
}

dependencies {
    implementation("org.controlsfx:controlsfx:11.1.0")
    implementation("com.dlsc.formsfx:formsfx-core:11.3.2") {
        exclude(group = "org.openjfx")
    }
    implementation("net.synedra:validatorfx:0.1.13") {
        exclude(group = "org.openjfx")
    }
    implementation("org.kordamp.ikonli:ikonli-javafx:12.2.0")
    implementation("org.kordamp.bootstrapfx:bootstrapfx-core:0.4.0")
    implementation("eu.hansolo:tilesfx:11.48") {
        exclude(group = "org.openjfx")
    }

    implementation(project(":api"))
}

application {
    // Define the main class for the application.
    mainClass.set("org.valdi.animedownloader.app.App")
}
