/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.valdi.animedownloader.java-application-conventions")
    id ("org.openjfx.javafxplugin") version "0.0.10"
}

javafx {
    version = "11.0.2"
    modules("javafx.controls", "javafx.fxml", "javafx.web")
}

dependencies {
    implementation("org.controlsfx:controlsfx:11.1.0")
    implementation("com.dlsc.formsfx:formsfx-core:11.3.2") {
        exclude(group = "org.openjfx")
    }
    implementation("net.synedra:validatorfx:0.1.13") {
        exclude(group = "org.openjfx")
    }
    implementation("org.kordamp.ikonli:ikonli-javafx:12.2.0")
    implementation("org.kordamp.bootstrapfx:bootstrapfx-core:0.4.0")
    implementation("eu.hansolo:tilesfx:11.48") {
        exclude(group = "org.openjfx")
    }

    implementation(project(":api"))
}

application {
    // Define the main class for the application.
    mainClass.set("org.valdi.animedownloader.app.App")
}
