/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.valdi.animedownloader.java-library-conventions")
    id("maven-publish")
}

dependencies {
    // https://mvnrepository.com/artifact/org.jsoup/jsoup
    implementation("org.jsoup:jsoup:1.14.3")
}

publishing {
    repositories {
        maven {
            name = "GitHubPackages"
            url = uri("https://maven.pkg.github.com/Valdi1111/anime-downloader")
            credentials {
                username = project.findProperty("gpr.user") as String? ?: System.getenv("GITHUB_USERNAME")
                password = project.findProperty("gpr.key") as String? ?: System.getenv("GITHUB_TOKEN")
            }
        }
    }
    publications {
        register<MavenPublication>("mavenJava") {
            groupId = "org.valdi"
            artifactId = "animedownloader-api"
            version = "1.0.0"

            from(components["java"])
        }
    }
}