/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.valdi.animedownloader.java-library-conventions")
    id("maven-publish")
}

dependencies {
    // https://mvnrepository.com/artifact/org.jsoup/jsoup
    implementation("org.jsoup:jsoup:1.14.3")
}

publishing {
    repositories {
        maven {
            name = "GitHubPackages"
            url = uri("https://maven.pkg.github.com/Valdi1111/anime-downloader")
            credentials {
                username = System.getenv("GITHUB_ACTOR")
                password = System.getenv("GITHUB_TOKEN")
            }
        }
    }
}
