/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.valdi.animedownloader.java-library-conventions")
}

dependencies {
    // https://mvnrepository.com/artifact/org.jsoup/jsoup
    implementation("org.jsoup:jsoup:1.14.3")
}
